version = 1

test_patterns = ["test/**"]

exclude_patterns = ["dist/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
